### ISSUE TITLE
Main branch of @Nauman702 is 12 commits behind this repository

### ISSUE THREAD

**Issue by oesteban** [nipraxis-fall-2022/diagnostics-NME#12]
Hi @Nauman702, I have figured out what is going on.

If you head to your fork of the repo (https://github.com/Nauman702/diagnostics-NME), you'll see that just above the code there's a message that states:

> This branch is [12 commits behind](https://github.com/Nauman702/diagnostics-NME/compare/main...nipraxis-fall-2022:diagnostics-NME:main) nipraxis-fall-2022:main.

This means that in your group's repository (this one, `nipraxis-fall-2022/diagnostics-NME`) there are some updates and you have not updated your `main` branch with them.

1. Do you understand what that means?
2. If so, do you need a walkthrough to update your main branch?

**Comment by Nauman702** [comment]
@oesteban thanks.
1. Yes I understood. I read about it on stackoverflow yesterday. But the solution they were giving, I was unable to see that option on my forked repo.
2. Yes please, I would appreciate.

**Comment by Nauman702** [comment]
@oesteban It looks like it is fixed and I created few PRs as well that were having issues.
