### ISSUE TITLE
group data-hash file

### ISSUE THREAD

**Issue by Nauman702** [nipraxis-fall-2022/diagnostics-NME#16]
@effigies Hi, our project repo has group-00 folder having its hash file. However, when I download the data via curl it downloads group-01 data and its hash file in the folder group-01. When I run validate data py file, it gives me an error on group-00 hash file. It's working fine after deleting it. Is something wrong in there?

Thanks

**Comment by effigies** [comment]
Yes, it looks like you need to remove the `group-00` directory, since your data came from `group-01`. I think we either need to update our process or our instructions to prevent multiple group directories.
