### ISSUE TITLE
sample outlier detector function output

### ISSUE THREAD

**Issue by Nauman702** [nipraxis-fall-2022/diagnostics-NME#18]
@jagruti8 @mtach Hi both, 
When I run my code with sample outlier detector function, I am getting the output as attached. It doesn't look right to me. Are you guys getting the same output?

Thank you 
![image](https://user-images.githubusercontent.com/30662450/191733527-0bbe1395-b629-409f-89d0-85d44da1ecc2.png)

**Comment by Nauman702** [comment]
I am having group-01 data and both my functions dvars and iqr_detector passed their tests.

**Comment by jagruti8** [comment]
@Nauman702 , is it using the default outlier detection code - iqr detector and dvars metric? - In this case yes, I am getting different results
Or you implemented ur own code?

**Comment by Nauman702** [comment]
@jagruti8 Yes I implemented dvars metric and iqr detector code and they are passing their tests. But apparently not giving correct output when I run find_outlier.py. Will check it again.

**Comment by Nauman702** [comment]
![image](https://user-images.githubusercontent.com/30662450/191733527-0bbe1395-b629-409f-89d0-85d44da1ecc2.png)
@matthew-brett Hi, it looks like I am not getting correct outliers on dvars and iqr_detector functions although both functions have passed their tests. Is there anything I am doing wrong? Thank you

**Comment by matthew-brett** [comment]
@effigies @oesteban - can either of you take a look?  Still lost in the conference.

**Comment by jagruti8** [comment]
@Nauman702 I tried implementing the dvars and iqr_detector that you have used, I get the results as expected. I guess you haven't yet merged the iqr_detector to the main?

**Comment by Nauman702** [comment]
@jagruti8 Thank you. The mistake was iqr_detector function should only return boolean values as you mentioned in #15 but the test_detetctor works both on integer and boolean values.

**Comment by Nauman702** [comment]
Now I am getting this output which looks like fine. 
![image](https://user-images.githubusercontent.com/30662450/192087213-0f881162-56a8-4f4e-8fad-94caffbbb6f4.png)
