### ISSUE TITLE
Ready for review

### ISSUE THREAD

**Issue by jagruti8** [nipraxis-fall-2022/diagnostics-NME#26]
Hi, @pxr687 @eilidhmacnicol @matthew-brett @effigies @oesteban - please can you review our project?

**Comment by jagruti8** [comment]
Hi, @pxr687 @eilidhmacnicol @matthew-brett @effigies @oesteban - I made some more changes to the code. If it is not yet reviewed its fine, else it would be great if the updated one can be reviewed again. Thanks

**Comment by oesteban** [comment]
Hi @jagruti8,

I can see 7 open issues by @Nauman702 and @mtach -- what is the expectation for those? The team should gather up and decide whether they can just be closed or merged in.

We will review the main branch as soon as the team can confirm that is what needs to be reviewed.

**Comment by jagruti8** [comment]
Hi @oesteban , yeah now the main branch can be reviewed. Thanks

**Comment by oesteban** [comment]
I'll be reviewing this project over the following days. Whenever I find something that could be addressed, I'll post new issues (e.g., #28)

**Comment by oesteban** [comment]
Note: I'll notify you when I'm done (and will also nudge the other course instructors)
